### ISSUE TITLE
color issue rows in issue list by priority

### ISSUE THREAD

**Issue by biohazardxxx** [FabriceSalvaire/redmine-improved-theme#13]
would be great if the rows in the issue list would be colored by the  priority.
like Low = green, high = red

**Comment by FabriceSalvaire** [comment]
tr tags have a _priority-..._ class thus it can be done easily. Note there is 6 priority levels.

Such customisation must be optional. You could do it with a custom SASS or CSS patch.

**Comment by FabriceSalvaire** [comment]
fixed in e8e2b7ff546709c4fbf287aa125da79920ecf4b3
