### ISSUE TITLE
Color statuses for issues

### ISSUE THREAD

**Issue by anton-reutov** [FabriceSalvaire/redmine-improved-theme#16]
implementing the color statuses for issues

For example screenshot
http://savepic.net/9001913.gif

**Comment by FabriceSalvaire** [comment]
see #13 

Such feature is more a personal matter, but I would accept a PR that implement an optional setting.

**Comment by FabriceSalvaire** [comment]
In fact, status-$i css classes have a meaning related to the redmine instance configuration. **Thus it should be done with a custom patch.**

see http://www.redmine.org/projects/redmine/wiki/HowTo_create_a_custom_Redmine_theme
